### ISSUE TITLE
Attack animation continues if defender is killed on first hit of Aether

### ISSUE THREAD

**Issue by chudooder** [chudooder/FEMultiplayer#1]
yep

**Comment by jedyobidan** [comment]
fixed

**Comment by chudooder** [comment]
it happened again young what u dong

**Comment by jedyobidan** [comment]
What was the seed? If it attacked with aether, killed, then attacked again, that's correct, because the second "hit" of aether is the sol effect

**Comment by chudooder** [comment]
oh, whoops, that's right then
