### ISSUE TITLE
Palette Swaps

### ISSUE THREAD

**Issue by jedyobidan** [chudooder/FEMultiplayer#14]
Can we get a Renderer.renderPaletteSwapped(Texture img, Texture origP, Texture newP) method?
I'd do it myself but Open GL makes no sense to me.
Something about a pixel/vertex shader.

**Comment by chudooder** [comment]
Currently hardcoded in. I need to figure out how to accurately read pixel data from images (it's returning the wrong color)

**Comment by jedyobidan** [comment]
Let's figure this out.

**Comment by jedyobidan** [comment]
HOORAY IT WORKS YAAAAAAY
