### ISSUE TITLE
Slick Color complaint

### ISSUE THREAD

**Issue by jedyobidan** [chudooder/FEMultiplayer#16]
Never change the argb values of a Color without cloning first. Otherwise bugs happen like crazy.

```
doSomething(Color c) {
    c.a = 0;
}

doSomething(Color.white); <= makes Color.white invisible forever.
```

wtffffffff

**Comment by jedyobidan** [comment]
All the bugs relating to this bullshit implementation problem have been fixed. Shawn, close this issue once you read it.

**Comment by chudooder** [comment]
Haha yeah, I noticed this when we had units fading out and the background for the mugshot changed.
