### ISSUE TITLE
UnitList design

### ISSUE THREAD

**Issue by chudooder** [chudooder/FEMultiplayer#26]
We shouldn't put all the selected units at the beginning of the list, since it messes up the location of the rest of the units. This makes finding the unit you want to add harder; besides, it isn't too difficult to find your selected units.

**Comment by chudooder** [comment]
This is not necessarily needed now because you can sort your units by name and class

**Comment by jedyobidan** [comment]
Not quite sure what you mean, but in the actual games your selected units are placed in the front. Besides, most likely you'll be building a team once, then saving it.
