### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by jedyobidan** [chudooder/FEMultiplayer#7]
WARN:class org.newdawn.slick.opengl.PNGImageData failed to read the data
for some of our sheets. should we be concerned?

**Comment by chudooder** [comment]
Which files are throwing the warning?

**Comment by chudooder** [comment]
Ended up just resaving the files

**Comment by jedyobidan** [comment]
Turns out its a bit depth issue. Had it again just recently. Make sure you save images in RGB mode (32 bit depth, 8 bits per channel), not indexed mode
